class ePOComputer {
    [System.Int32]    $ParentID
    [System.String]   $ComputerName
    [System.String]   $Description
    [System.String]   $SystemDescription
    [System.String]   $TimeZone
    [System.String]   $DefaultLangID
    [System.String]   $UserName
    [System.String]   $DomainName
    [System.String]   $IPHostName
    [System.String]   $IPV6
    [System.String]   $IPAddress
    [System.String]   $IPSubnet
    [System.String]   $IPSubnetMask
    [System.String]   $IPV4x
    [System.String]   $IPXAddress
    [System.String]   $SubnetAddress
    [System.String]   $SubnetMask
    [System.String]   $NetAddress
    [System.String]   $OSType
    [System.String]   $OSVersion
    [System.String]   $OSServicePackVer
    [System.String]   $OSBuildNum
    [System.String]   $OSPlatform
    [System.String]   $OSOEMID
    [System.String]   $CPUType
    [System.String]   $CPUSpeed
    [System.String]   $NumOfCPU
    [System.String]   $CPUSerialNum
    [System.Double]   $TotalPhysicalMemory
    [System.Double]   $FreeMemory
    [System.Double]   $FreeDiskSpace
    [System.Double]   $TotalDiskSpace
    [System.Boolean]  $IsPortable
    [System.Boolean]  $Vdi
    [System.String]   $OSBitMode
    [System.String]   $LastAgentHandler
    [System.String]   $UserProperty1
    [System.String]   $UserProperty2
    [System.String]   $UserProperty3
    [System.String]   $UserProperty4
    [System.String]   $UserProperty5
    [System.String]   $UserProperty6
    [System.String]   $UserProperty7
    [System.String]   $UserProperty8
    [System.String]   $SysvolFreeSpace
    [System.String]   $SysvolTotalSpace
    [System.String[]] $Tags
    [System.String[]] $ExcludedTags
    [System.DateTime] $LastUpdate
    [System.Boolean]  $ManagedState
    [System.Guid]     $AgentGUID
    [System.Version]  $AgentVersion
    [System.String]   $AutoID
}